"""recreate ai_estimates

Revision ID: 795fcf0728c5
Revises: 20260624_0001
Create Date: 2026-06-26 16:14:09.224567
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '795fcf0728c5'
down_revision: Union[str, None] = '20260624_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_estimates',
    sa.Column('estimate_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_urls', sa.JSON(), nullable=True),
    sa.Column('main_category', sa.String(length=50), nullable=True),
    sa.Column('object_label', sa.String(length=100), nullable=True),
    sa.Column('problem_label', sa.String(length=100), nullable=True),
    sa.Column('repair_task_name', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('min_price', sa.Integer(), nullable=True),
    sa.Column('max_price', sa.Integer(), nullable=True),
    sa.Column('estimated_minutes_min', sa.Integer(), nullable=True),
    sa.Column('estimated_minutes_max', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('estimate_status', sa.String(length=20), server_default='PROCESSING', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_ai_estimates_user_id_users')),
    sa.PrimaryKeyConstraint('estimate_id', name=op.f('pk_ai_estimates'))
    )
    op.create_index(op.f('ix_ai_estimates_user_id'), 'ai_estimates', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_estimates_user_id'), table_name='ai_estimates')
    op.drop_table('ai_estimates')
    # ### end Alembic commands ###
